spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://172.26.128.2:3306/one_home_pet_dev_pet?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: withoutcat
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/